# Generated by Django 3.0.3 on 2020-03-13 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_ingresso', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pessoafisica',
            name='cpf',
            field=models.CharField(blank=True, max_length=11, null=True, verbose_name='CPF'),
        ),
        migrations.AlterField(
            model_name='evento',
            name='nome',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name='Nome'),
        ),
        migrations.AlterField(
            model_name='evento',
            name='sigla',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name='Sigla'),
        ),
        migrations.AlterField(
            model_name='ingresso',
            name='descrição',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name='Descrição'),
        ),
        migrations.AlterField(
            model_name='ingresso',
            name='valor',
            field=models.FloatField(blank=True, max_length=40, null=True, verbose_name='Valor'),
        ),
        migrations.AlterField(
            model_name='pessoa',
            name='nome',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name='Nome'),
        ),
    ]
