# Generated by Django 3.0.3 on 2020-03-13 23:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_ingresso', '0002_auto_20200313_2032'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingresso',
            name='evento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Evento', to='app_ingresso.Evento'),
        ),
    ]
