# Generated by Django 3.0.3 on 2020-03-13 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_ingresso', '0003_ingresso_evento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pessoafisica',
            name='cpf',
            field=models.CharField(blank=True, max_length=14, null=True, verbose_name='CPF'),
        ),
    ]
