# Generated by Django 3.0.3 on 2020-03-13 23:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_ingresso', '0004_auto_20200313_2055'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inscrição',
            name='evento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app_ingresso.Evento', verbose_name='Evento'),
        ),
        migrations.AlterField(
            model_name='inscrição',
            name='ingresso',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app_ingresso.Ingresso', verbose_name='Ingresso'),
        ),
        migrations.AlterField(
            model_name='inscrição',
            name='pessoa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app_ingresso.Pessoa', verbose_name='Pessoa'),
        ),
    ]
