# Generated by Django 3.0.3 on 2020-03-14 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_ingresso', '0005_auto_20200313_2059'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evento',
            name='sigla',
            field=models.CharField(blank=True, max_length=5, null=True, verbose_name='Sigla'),
        ),
        migrations.AlterField(
            model_name='ingresso',
            name='valor',
            field=models.FloatField(blank=True, max_length=6, null=True, verbose_name='Valor'),
        ),
    ]
